### ISSUE TITLE
Pre-commit is not working properly

### ISSUE THREAD

**Issue by erikmannerfelt** [erikmannerfelt/rsgpr#33]
Pre-commit has stopped working. Maybe fixable by just updating everything?

```bash
beautysh.................................................................Failed
- hook id: beautysh
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo3we8pamt/py_env-python3.12/bin/beautysh", line 5, in <module>
    from beautysh import main
  File "/home/runner/.cache/pre-commit/repo3we8pamt/py_env-python3.12/lib/python3.12/site-packages/beautysh/__init__.py", line 9, in <module>
    import pkg_resources  # part of setuptools
    ^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'

Pretty format YAML.......................................................Failed
- hook id: pretty-format-yaml
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo9838j_so/py_env-python3.12/bin/pretty-format-yaml", line 5, in <module>
    from language_formatters_pre_commit_hooks.pretty_format_yaml import pretty_format_yaml
  File "/home/runner/.cache/pre-commit/repo9838j_so/py_env-python3.12/lib/python3.12/site-packages/language_formatters_pre_commit_hooks/__init__.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by erikmannerfelt** [comment]
Now it's just `beautysh` that doesn't work so I assume that it's the tool's fault. I'll try to re-introduce it again later.
